#pragma config(Sensor, S1,     Button,         sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[motorC]=100;
	motor[motorB]=100;
	wait1Msec(5000);
	if(SensorValue(button) == 1)
	{
		motor[motorC]=-99;
		motor[motorB]=-99;
		wait10Msec(500);
		motor[motorB]=-90;
		motor[motorC]=60;
		wait1Msec(3500);
	}




}
