#pragma config(Motor,  motorB,          Left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          Right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		motor[Left]= 100;
		motor[Right]= 100;
		wait10Msec(1000);
		motor[Left]= -100;
		motor[Right]= -100;
		wait10Msec(1000);
	}
}
