#pragma config(Sensor, S1,     button,         sensorEV3_Touch)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[motorC]=80;
	motor[motorB]=100;
	wait1Msec(3000);
	motor[motorC]=-80;
	motor[motorB]=-100;
	wait1Msec(3000);
	motor[motorC]=90;
	motor[motorB]=90;
	wait1Msec(1500);
	motor[motorC]=-80;
	motor[motorB]=100;
	wait1Msec(3000);
	motor[motorB]=40;
	motor[motorC]=100;
	wait1Msec(6000);
	motor[motorB]=50;
	motor[motorC]=100;
	wait1Msec(1000);
	motor[motorB]=60;
	motor[motorC]=100;
	wait1Msec(1000);
	motor[motorB]=70;
	motor[motorC]=100;
	wait1Msec(2000);
	motor[motorB]=80;
	motor[motorC]=100;
	wait1Msec(6000);
	if(SensorValue(button) == 1)
	{
		motor[right]=-90;
		motor[left]=-90;
		motor[left]=100;
		motor[right]=60;
		wait1Msec(3500);
	}

}
