#pragma config(Sensor, S2,     Lbat,           sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     Fbat,           sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     Rbat,           sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		if(SensorValue(Rbat) <= 5)
		{
motor[left]=47;
motor[motorC]=50;
wait1Msec(1000);
}
else(sensorvalue(Lbat) >= 5)
	motor[left]=50;
	motor[right]=47;
	wait10msec(.2);
{
	motor(left)=60;
	motor(right)=60;
}
}
}
