#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int speed = 10;
	while(speed <= 100)
	{
		motor[left] = speed;
		motor[right] = speed;
		wait1Msec(1000);

		speed = speed + 10;
}
}
