#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	int speed = 15;
	int speed2 = 5;
	while(true)
	{
		motor[left] = speed;
		motor[right] = speed2;
		wait10Msec(500);

		speed = speed + 10;
		speed2 = speed2 + 10;
	if(mode == GOING)
	{
		if(getMotorEncoder(right)= 18000)
		{
			mode =
}

}
