#pragma config(Sensor, S1,     lbat,           sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     fbat,           sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     rbat,           sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	int mode = 1;
	while(true)
	{
		if(mode == 1)
		{
			int speed = 5;
			int speed2 = 15;
			while(true)
			{
				motor[left] = speed;
				motor[right] = speed2;
				wait10Msec(500);

				speed = speed + 10;
				speed2 = speed2 + 10;

				if(sensorvalue (rbat) < 8 )
				{ mode == 2;
					if(SensorValue(rbat) <= 6)
					{
						motor[left]=47;
						motor[right]=50;
						wait1Msec(1000);
						{
							(SensorValue(Rbat) >= 7);
							{
								motor[left]=50;
								motor[right]=47;
								wait10Msec(.2);
							}
						}
					}
				}
			}

		}
	}
}
